import {
  ALargeSmall,
  AlignLeft,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bell,
  BookOpen,
  BookOpenText,
  ChartNoAxesColumn,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CirclePlus,
  ClipboardList,
  Clock,
  Cloud,
  Coins,
  Copy,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  Filter,
  Folder,
  FolderInput,
  FolderPlus,
  Globe,
  GraduationCap,
  Heart,
  Highlighter,
  Hourglass,
  House,
  Info,
  Key,
  Layers,
  LayoutGrid,
  LibraryBig,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MessageCircle,
  Moon,
  Pencil,
  Plus,
  Quote,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share,
  ShieldCheck,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Type,
  User,
  Volume2,
  ArrowDownUp,
  X,
} from "lucide-react";

/**
 * Icônes Lucide (ISC), trait 1,75, couleur héritée du texte. Toujours décoratives ou
 * accompagnées d'un libellé. Seules les icônes listées ici entrent dans le build.
 */
const ICONS = {
  // Interface
  share: Share,
  learning: GraduationCap,
  "quiz-v4": ListChecks,
  folder: Folder,
  "folder-plus": FolderPlus,
  hourglass: Hourglass,
  move: FolderInput,
  home: House,
  book: BookOpen,
  user: User,
  plus: Plus,
  back: ChevronLeft,
  arrow: ArrowRight,
  "arrow-left": ArrowLeft,
  close: X,
  file: File,
  search: Search,
  chat: MessageCircle,
  check: Check,
  chevron: ChevronRight,
  more: Ellipsis,
  download: Download,
  link: Link,
  clock: Clock,
  moon: Moon,
  sun: Sun,
  settings: Settings,
  shield: ShieldCheck,
  logout: LogOut,
  cloud: Cloud,
  filter: Filter,
  sort: ArrowDownUp,
  info: Info,
  alert: TriangleAlert,
  refresh: RefreshCw,
  star: Star,
  eye: Eye,
  list: List,
  spark: Sparkles,
  quiz: ClipboardList,
  heart: Heart,
  volume: Volume2,
  copy: Copy,
  trash: Trash2,
  kebab: EllipsisVertical,
  aa: Type,
  bell: Bell,
  send: Send,
  mail: Mail,
  lock: Lock,
  "plus-circle": CirclePlus,
  layers: Layers,
  grid: LayoutGrid,
  bulb: Lightbulb,
  lines: AlignLeft,
  globe: Globe,
  "eye-off": EyeOff,
  pencil: Pencil,
  key: Key,
  sliders: SlidersHorizontal,
  "text-size": ALargeSmall,
  bars: ChartNoAxesColumn,

  // Sections
  library: LibraryBig,
  credits: Coins,
  admin: ShieldCheck,

  // Rôles pédagogiques (couleur du rôle dans le lecteur)
  definition: BookOpenText,
  formula: Sigma,
  "key-idea": Star,
  caution: TriangleAlert,
  example: Lightbulb,
  analogy: ArrowLeftRight,
  retain: Highlighter,
  success: CircleCheck,
  source: Quote,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];

export function Icon({ name, size = 22, className }: { name: IconName; size?: number; className?: string }) {
  const Glyph = ICONS[name];
  return (
    <Glyph
      size={size}
      strokeWidth={1.75}
      aria-hidden="true"
      focusable="false"
      className={className ? `icon ${className}` : "icon"}
    />
  );
}
